server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}/furnitureDB
    password: ${TRAINING_DB_PASSWORD}
    username: ${TRAINING_DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true